# Generated by Django 5.0.6 on 2025-01-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='rolls_in', to='api.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exams_taken',
            field=models.ManyToManyField(blank=True, null=True, related_name='takes', to='api.exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='have', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.subject'),
        ),
    ]
