# Generated by Django 5.1.5 on 2025-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
