# Generated by Django 5.0.6 on 2025-01-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_student_id_student_student_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='rolls_in', to='api.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exams_taken',
            field=models.ManyToManyField(blank=True, related_name='takes', to='api.exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
